enc:
  required: True
  type: dict
  schema:
    autosize:
      required: False
      type: boolean
    size:
      required: True
      type: list
      maxlength: 2
      schema:
        type: float
        min: 1.0

    origin:
      required: True
      excludes: center
      type: list
      maxlength: 2
      schema:
        type: float

    center:
      required: True
      excludes: origin
      type: list
      maxlength: 2
      schema:
        type: float

    FGDB_depths:
      required: False
      type: list
      minlength: 1
      schema:
        type: integer
        min: 0

    S57_layers:
      required: False
      type: list
      minlength: 1
      schema:
        type: string

    resources:
      required: False
      type: list
      minlength: 1
      schema:
        type: string

display:
  required: False
  type: dict
  schema:
    colorbar:
      required: False
      type: boolean

    dark_mode:
      required: False
      type: boolean

    fullscreen:
      required: False
      type: boolean

    resolution:
      required: False
      type: integer

    anchor:
      required: False
      type: string

    dpi:
      required: False
      type: integer
