enc:
  autosize: True
  size: [ 16.0, 12.0, ]
  center: [ -87.01, 24.88 ]
  #Only one of these attributes allowed TODO: check if yaml offers single choice structure
  #FGDB_depths: [ 0, 1 , 5, 20]
  S57_layers: ["DEPARE", "LNDARE", "TSSLPT"]
  resources: [ "data/", "data/db/" ]

display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  resolution: 640
  anchor: "center"
  dpi: 96
