enc:
  #autosize: True #TODO: implement autosize
#  size: [ 16.0, 12.0, ]
  size: [ 22.0, 15.5 ]
  origin: [ -98.0, 18.0 ]
#  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
  depths: [ 0, 50, 100, 200, 2000 ]
  #UTM_zone: 33
  S57_layers: ["DEPARE", "LNDARE", "TSSLPT"]
  resources: [ "data/", "data/db/" ]

display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  resolution: 640
  anchor: "center"
  dpi: 96
