enc:
# TODO: implement autosize
# test config for S-57
  size: [ 3.5, 3.5 ]
  origin: [ -96.7, 27.0 ]
  depths: [ 0, 1 ]
  crs: "WGS84"
  S57_layers: ["DEPARE", "LNDARE", "TSSLPT"]
  resources: [ "data/", "data/db/" ]
  weather:
    PyThor_adress: "http://127.0.0.1:5000"
    time_start: 1717420980
    time_end: 1717420980
    latitude_start: 36
    latitude_end: 37
    longitude_start: 15
    longitude_end: 16
    variables: [ "wave_direction","wave_height","wave_period","wind_direction","wind_speed" ]

# test config for FGDB
#  size: [ 9000, 5062 ]
#  center: [ 44300, 6956450 ]
#  depths: [ 0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500 ]
#  crs: "UTM33N"
#  resources: [ "/", "data/", "data/db/" ]
display:
  colorbar: False
  dark_mode: True
  fullscreen: False
  resolution: 640
  anchor: "center"
  dpi: 96



